# -*- coding: utf-8 -*-
"""Final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ZX5uMsFIONmXluJlU5F5YRPckJFxLJN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Swiss Coding/Final project/new final.csv')

df.head()

df.info()

df.describe()

# Convert date
df['order_date'] = pd.to_datetime(df['order_date'])


# Create additional columns
df['month'] = df['order_date'].dt.to_period('M')
df['discount_bucket'] = pd.cut(df['discount_percent'],
                               bins=[0,10,20,30,40,50],
                               labels=['0-10%','10-20%','20-30%','30-40%','40-50%'])



#Q1: Which categories generate highest revenue?

category_sales = df.groupby('category')[['revenue_usd','units_sold']].sum().sort_values(by='revenue_usd', ascending=False)
print(category_sales)

category_sales['revenue_usd'].plot(kind='bar', title='Revenue by Category')
plt.show()

#Q2: Top-performing brands & models

brand_sales = df.groupby('brand')['revenue_usd'].sum().sort_values(ascending=False).head(10)
print(brand_sales)

#Q2: Top-performing brands & models

model_sales = df.groupby('model_name')['revenue_usd'].sum().sort_values(ascending=False).head(10)
print(model_sales)

#Q3: Revenue by country
country_sales = df.groupby('country')['revenue_usd'].sum().sort_values(ascending=False)
print(country_sales)

country_sales.head(10).plot(kind='bar', title='Top Countries by Revenue')
plt.show()

#Q4: Impact of discount on sales
discount_analysis = df.groupby('discount_percent')[['units_sold','revenue_usd']].mean()
print(discount_analysis)

discount_analysis.plot(title='Discount vs Sales')
plt.show()

#Q5: Optimal discount range
discount_bucket_analysis = df.groupby('discount_bucket')[['revenue_usd','units_sold']].mean()
print(discount_bucket_analysis)

discount_bucket_analysis.plot(kind='bar', title='Discount Bucket Performance')
plt.show()

#Q6: Revenue by income level
income_sales = df.groupby('customer_income_level')['revenue_usd'].sum().sort_values(ascending=False)
print(income_sales)

income_sales.plot(kind='bar', title='Revenue by Income Level')
plt.show()

#Q7: Customer rating impact
rating_analysis = df.groupby('customer_rating')[['revenue_usd','units_sold']].mean()
print(rating_analysis)

rating_analysis.plot(title='Rating vs Sales')
plt.show()

#Q8: Buying behavior by gender

gender_sales = df.groupby('gender')[['revenue_usd','units_sold']].sum()
print(gender_sales)

gender_sales.plot(kind='bar', title='Sales by Gender')
plt.show()

#Q9: Sales channel performance
channel_sales = df.groupby('sales_channel')[['revenue_usd','units_sold']].sum()
print(channel_sales)

channel_sales.plot(kind='bar', title='Sales by Channel')
plt.show()

#Q10: Payment method analysis

payment_sales = df.groupby('payment_method')[['revenue_usd','units_sold']].sum()
print(payment_sales)

payment_sales.plot(kind='bar', title='Payment Method Performance')
plt.show()

corr = df[['base_price_usd','discount_percent','units_sold','revenue_usd','customer_rating']].corr()
print(corr)

#Correlation of 4 factors
corr = df[['base_price_usd','discount_percent','units_sold','revenue_usd']].corr()
print(corr)

sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

df.to_csv('new_project.csv', index=False)

from google.colab import files
files.download('new_project.csv')