# -*- coding: utf-8 -*-
"""final project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJyLCccvzOCRbD7Kx_whl2ru1PpFOloF
"""

# import lib
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data

from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/MyDrive/Swiss Coding/Final project/final_project.xlsx')

# Load data
df.head(5)

df.info()

df.describe()

df['Selected'] = (df['Final_Decision'] == 'Selected').astype(int)

# Calculate correlation

correlation_matrix = df[['CGPA','Experience_Years','Skills_Score','Interview_Score','Selected']].corr()

correlation_matrix

# QUESTION 1: What drives hiring decisions?


plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title("Selected through factors Correlation Matrix")
plt.show()

df.groupby('Selected')[['CGPA','Experience_Years','Skills_Score','Interview_Score']].mean()

# QUESTION 2: Selection rate
selection_rate = df['Selected'].mean()
print(selection_rate)

# QUESTION 3: Selection rate BY JOB ROLE


df.groupby('Job_Applied')['Selected'].mean().sort_values(ascending=False)

#QUESTION 4: Bias (Gender / University)

rate_gender = df.groupby('Gender')['Selected'].mean()
print(rate_gender)

#QUESTION 4: Bias (Gender / University)

rate_uni = df.groupby('University')['Selected'].mean().sort_values(ascending=False)
print(rate_uni)

df.groupby('Gender')[['Skills_Score','Interview_Score']].mean()

df.groupby('University')[['Skills_Score','Interview_Score']].mean()

#Total selected ratio by qualiifications

rate_edu = df.groupby('Education_Level')['Final_Decision'] \
             .apply(lambda x: (x == 'Selected').mean())

print(rate_edu)

# QUESTION 5: Most competitive roles
df.groupby('Job_Applied').agg({
    'Selected': 'mean',
    'Interview_Score': 'mean',
    'Skills_Score': 'mean'
}).sort_values(by='Selected')

#Total job applied

job_counts = df['Job_Applied'].value_counts()

print(job_counts)

#Logic Regegression - Hồi quy Logistic
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = df[['CGPA','Experience_Years','Skills_Score','Interview_Score']]
y = df['Selected']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression()
model.fit(X_train, y_train)

model.score(X_test, y_test)

# # QUESTION 6: Predict candidate success? (Mô hình tuyến tính)
original_features = ['CGPA','Experience_Years','Skills_Score','Interview_Score']

pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.coef_[0]
})

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# ── Data from your latest model output ────────────────
data = {
    'Feature': ['CGPA', 'Experience_Years', 'Skills_Score', 'Interview_Score'],
    'Coefficient': [0.0717376, 0.0488867, -0.0008830, -0.0059589]
}

df = pd.DataFrame(data)

# Absolute value for bar length, sign for color & label
df['Abs_Coefficient'] = np.abs(df['Coefficient'])

# Sort: strongest absolute impact at top
df = df.sort_values('Abs_Coefficient', ascending=True)

# Colors: green = helps selection, red = hurts when higher
colors = ['#4caf50' if coef >= 0 else '#ff5252' for coef in df['Coefficient']]

# ── Plot ───────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10.5, 5.5), facecolor='#0d1117')
ax.set_facecolor('#161b22')

bars = ax.barh(df['Feature'], df['Abs_Coefficient'],
               color=colors, height=0.65,
               edgecolor='white', linewidth=0.6)

# Add coefficient labels (with sign)
for bar, coef, abs_val in zip(bars, df['Coefficient'], df['Abs_Coefficient']):
    if coef >= 0:
        ax.text(abs_val + 0.002, bar.get_y() + bar.get_height()/2,
                f'+{coef:.6f}', va='center', ha='left',
                fontsize=10.5, color='white', fontweight='medium')
    else:
        ax.text(abs_val + 0.002, bar.get_y() + bar.get_height()/2,
                f'{coef:.6f}', va='center', ha='left',
                fontsize=10.5, color='white', fontweight='medium')

# ── Styling ────────────────────────────────────────────
ax.set_title("What Really Predicts Getting Hired?\n"
           "(Logistic Regression Coefficients)",
             fontsize=15, fontweight='bold', color='white', pad=18)

ax.set_xlabel("Absolute Coefficient Magnitude\n"
             ,
              fontsize=11, color='white', labelpad=12)

ax.tick_params(axis='both', colors='white', labelsize=10.5)
ax.invert_yaxis()

# Annotation
ax.text(0.055, -0.28,

        "→ CGPA & Experience_Years are now the dominant positive drivers.",
        fontsize=9.8, color='#bbdefb', style='italic',
        transform=ax.transAxes,
        bbox=dict(facecolor='#1e293b', edgecolor='none', pad=7, alpha=0.8))

# Clean look
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#4a5568')
ax.spines['bottom'].set_color('#4a5568')

plt.tight_layout()
plt.show()

#7. What combination leads to success?
df.groupby('Selected')[['Skills_Score','Interview_Score','Experience_Years']].mean()

# 8. Top 10 most universities selected
df.groupby(['University'])['Selected'].mean() \
  .sort_values(ascending=False) \
  .head(10)

# 9. Where do rejected candidates fail?
import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(x='Skills_Score', y='Interview_Score', hue='Selected', data=df)
plt.show()

#10. What improves hiring decisions?
from sklearn.linear_model import LogisticRegression

X = df[['Skills_Score','Interview_Score']]
y = df['Selected']

model = LogisticRegression()
model.fit(X, y)

print(model.coef_)

import matplotlib.pyplot as plt
import numpy as np

# Data from your model
features = ['Skills_Score', 'Interview_Score']
coefs    = [-0.00089915, -0.00634405]
abs_coefs = np.abs(coefs)

# ───────────────────────────────────────────────
plt.figure(figsize=(9, 4.5), facecolor='#0d1117')
ax = plt.gca()
ax.set_facecolor('#161b22')

bars = ax.barh(features, abs_coefs,
               color=['#FF8C42', '#4EA8DE'],
               height=0.65, edgecolor='white', linewidth=0.8)

# Value labels on bars
for bar in bars:
    width = bar.get_width()
    ax.text(width + 0.00015, bar.get_y() + bar.get_height()/2,
            f'{width:.8f}',
            va='center', ha='left', fontsize=10.5,
            color='white', fontweight='medium')

# Styling
ax.set_title('What Actually Improves Hiring Decisions?\n'
            '(Absolute Logistic Regression Coefficients)',
             fontsize=15, fontweight='bold', color='white', pad=20)

ax.set_xlabel('Absolute Coefficient Magnitude\n',
              fontsize=11, color='white', labelpad=12)

ax.tick_params(axis='both', colors='white', labelsize=10)
ax.invert_yaxis()  # strongest on top

# Remove top/right spines
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#444c56')
ax.spines['bottom'].set_color('#444c56')

plt.tight_layout()
plt.show()

df.to_csv('final_project.csv', index=False)

from google.colab import files
files.download('final_project.csv')

df.groupby('Selected')[['Skills_Score','Interview_Score']].mean()

# 6. VISUAL 5 — Skills vs Interview (Scatter Plot)

import matplotlib.pyplot as plt

# Data
means = df.groupby('Selected')[['Skills_Score','Interview_Score']].mean()

# Plot
means.plot(kind='bar')

plt.title('Average Scores by Selection Status')
plt.xlabel('Selected (0 = Rejected, 1 = Selected)')
plt.ylabel('Average Score')
plt.xticks(rotation=0)
plt.legend(title='Score Type')

plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Reset index for seaborn
means = df.groupby('Selected')[['Skills_Score','Interview_Score']].mean().reset_index()

# Convert to long format
means_melted = means.melt(id_vars='Selected',
                          var_name='Score Type',
                          value_name='Score')

# Plot
sns.barplot(data=means_melted, x='Selected', y='Score', hue='Score Type')

plt.title('Skills vs Interview Scores by Selection')
plt.xlabel('Selected (0 = Rejected, 1 = Selected)')
plt.ylabel('Average Score')

plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data (shortened job names for readability)
data = {
    'Job': [
        'AI Ethics & Compliance',
        'NLP Engineer',
        'AI Research Scientist',
        'AI Product Manager',
        'Data Architect (AI Infra)',
        'ML Engineer',
        'Reinforcement Learning',
        'Computer Vision Engineer',
        'MLOps Engineer',
        'Deep Learning Specialist'
    ],
    'Selected (%)': [52.88, 53.92, 56.76, 57.00, 57.29, 57.53, 59.47, 59.55, 60.70, 61.69]
}

df = pd.DataFrame(data).sort_values('Selected (%)')

# Plot
plt.figure(figsize=(11, 6.5))
colors = sns.color_palette('rocket_r', len(df))   # dark → light = more → less competitive

bars = plt.barh(df['Job'], df['Selected (%)'], color=colors)

plt.xlabel('Selection Rate (%)   ← lower = more applicants per offer', fontsize=11)
plt.title('Job Roles – Competitiveness by Selection Rate', fontsize=13, pad=12)
plt.gca().invert_yaxis()  # most competitive at top

# Value labels
for bar in bars:
    plt.text(bar.get_width() + 0.4, bar.get_y() + bar.get_height()/2,
             f'{bar.get_width():.1f}%',
             va='center', fontsize=10, fontweight='bold')

# Average line
avg = df['Selected (%)'].mean()
plt.axvline(avg, color='gray', ls='--', alpha=0.7, lw=1.2)
plt.text(avg + 0.6, 0.05, f'Avg: {avg:.1f}%', color='gray', fontsize=9.5)

sns.despine()
plt.tight_layout()
plt.show()